_target_: pytorch_lightning.Trainer
deterministic: warn
strategy: ddp_find_unused_parameters_true
limit_val_batches: 1000
val_check_interval: 0.1
max_epochs: 50
precision: 16-mixed
accumulate_grad_batches: 32
callbacks:
  - _target_: pytorch_lightning.callbacks.LearningRateMonitor
  - _target_: pytorch_lightning.callbacks.EarlyStopping
    monitor: val_RetrievalMAP
    mode: max
    patience: 5
    verbose: True
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val_RetrievalMAP
    mode: max
    save_top_k: 1
    verbose: True
  - _target_: pytorch_lightning.callbacks.TQDMProgressBar
    refresh_rate: 1
