defaults:
  - _self_
  - ranker/encoder@doc_encoder: transformer
  - encoding_data: h5_corpus
  - index_writer: fast_forward

device: cuda
ckpt_path: ???

data_processor:
  _target_: model.DualEncoderDataProcessor
  char_limit: null

data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: 512
  num_workers: 1
  shuffle: False

hydra:
  job:
    chdir: True
