defaults:
  - _self_
  - ranker: dual_encoder
  - encoding_data: h5_corpus

device: cuda
ckpt_path: ???

data_loader:
  _target_: torch.utils.data.DataLoader
  batch_size: 512
  num_workers: 16
  shuffle: False

hydra:
  job:
    chdir: True
