defaults:
  - _self_
  - ranker/encoder@query_encoder: transformer
  - ff_index_reader: from_disk

dataset: ???
metrics: ???

device: cpu
model_id: ???
ckpt_file: ???
sparse_scores_file: ???

cutoff_sparse: 1000
alpha: [0, 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1]
cutoff: null
early_stopping: False

hydra:
  job:
    chdir: True
