defaults:
  - _self_
  - ranker/encoder@query_encoder: transformer

ckpt_path: ???
name: ???
index_dir: ???
dataset: ???
sparse_runfile: ???

metrics: []
device: cpu

cutoff_sparse: 1000
alpha: [0, 0.001, 0.01, 0.1, 1]

hydra:
  job:
    chdir: True
