defaults:
  - _self_
  - ranker/encoder@query_encoder: transformer

dataset: ???
metrics: []

device: cpu
name: ???
ckpt_file: ???
index_dir: ???
k: 1000
batch_size: 32

hydra:
  job:
    chdir: True
