defaults:
  - _self_
  - ranker/encoder@query_encoder: transformer

ckpt_path: ???
name: ???
index_dir: ???
dataset: ???

query_attribute: text
metrics: []
device: cpu
k: 1000
batch_size: 32

hydra:
  job:
    chdir: True
