defaults:
  - _self_
  - ranker: dual_encoder
  - training_data: h5
  - trainer: fine_tuning

random_seed: 123
ckpt_path: null

hydra:
  job:
    chdir: True

  run:
    dir: /scratch/bovandenberg/dual-encoders/train_estimator/
