tokenizer:
  _target_: model.transformer.TransformerTokenizer
  pretrained_model: ${..pretrained_model}
  max_length: 512

encoder:
  _target_: model.transformer.TransformerEncoder
  pretrained_model: ${..pretrained_model}
  dense_layer_dim: null

pretrained_model: castorini/tct_colbert-msmarco
